default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: sightseer_development
  username: tomlee
  password:

test:
  <<: *default
  database: sightseer_test
  username: tomlee
  password:

production:
  <<: *default
  database: sightseer_production
  username: tomlee
  password:
